module.exports = () => ({
    mostRecentStoriesViewed: true,
    pageLength: 10,
    unreadStoryCount: 0,
    totalStories: 133,
    postStoryStatus: 0,
    storiesFirstPageReady: true,
    storiesStatus: 2,
    stories: [
        {
            eventMetadata: "",
            eventZCoordinate: 0,
            eventYCoordinate: 0,
            eventXCoordinate: 0,
            eventHasCoordinates: false,
            eventPlayerXuids: [],
            isEventLoaded: false,
            isEvent: false,
            reportToXboxStatus: 0,
            reportToClubOwnerStatus: 0,
            deleteStatus: 0,
            toggleLikeStatus: 0,
            hasLiked: false,
            setViewedStatus: 0,
            hasViewed: true,
            commentsStatus: 0,
            totalComments: 0,
            totalLikes: 0,
            body: "when is this back? last post was over a year ago",
            imageStatus: 2,
            image: "",
            timePostedNarration: "Posted on July 13, 2025",
            timePosted: "Jul 13 2025",
            authorXuid: "2535438939106521",
            id: "userposts.xboxlive.com/users/xuid(2535438939106521)/posts/dae1e329-b951-46c6-93ba-a049c3669015/timelines/Club/3379879717831650",
        },
        {
            eventMetadata: "",
            eventZCoordinate: 0,
            eventYCoordinate: 0,
            eventXCoordinate: 0,
            eventHasCoordinates: false,
            eventPlayerXuids: [],
            isEventLoaded: false,
            isEvent: true,
            reportToXboxStatus: 0,
            reportToClubOwnerStatus: 0,
            deleteStatus: 0,
            toggleLikeStatus: 0,
            hasLiked: false,
            setViewedStatus: 0,
            hasViewed: true,
            commentsStatus: 0,
            totalComments: 0,
            totalLikes: 0,
            body: "There was a Realm Event. Check out the Story Feed in Minecraft to see what happened. NewMember",
            imageStatus: 2,
            image: "",
            timePostedNarration: "Posted on April 3, 2025",
            timePosted: "Apr 3 2025",
            authorXuid: "2535460414733092",
            id: "userposts.xboxlive.com/users/xuid(2535460414733092)/posts/172dc832-9d27-4dfd-a2bc-a899cdddd37a/timelines/Club/3379879717831650",
        },
        {
            eventMetadata: "",
            eventZCoordinate: 0,
            eventYCoordinate: 0,
            eventXCoordinate: 0,
            eventHasCoordinates: false,
            eventPlayerXuids: [],
            isEventLoaded: false,
            isEvent: true,
            reportToXboxStatus: 0,
            reportToClubOwnerStatus: 0,
            deleteStatus: 0,
            toggleLikeStatus: 0,
            hasLiked: false,
            setViewedStatus: 0,
            hasViewed: true,
            commentsStatus: 0,
            totalComments: 0,
            totalLikes: 0,
            body: "There was a Realm Event. Check out the Story Feed in Minecraft to see what happened. NewMember",
            imageStatus: 2,
            image: "",
            timePostedNarration: "Posted on April 3, 2025",
            timePosted: "Apr 3 2025",
            authorXuid: "2535460414733092",
            id: "userposts.xboxlive.com/users/xuid(2535460414733092)/posts/e39b59f2-c7f5-4d26-9099-b214cd14a211/timelines/Club/3379879717831650",
        },
        {
            eventMetadata: "",
            eventZCoordinate: 0,
            eventYCoordinate: 0,
            eventXCoordinate: 0,
            eventHasCoordinates: false,
            eventPlayerXuids: [],
            isEventLoaded: false,
            isEvent: false,
            reportToXboxStatus: 0,
            reportToClubOwnerStatus: 0,
            deleteStatus: 0,
            toggleLikeStatus: 0,
            hasLiked: true,
            setViewedStatus: 0,
            hasViewed: true,
            commentsStatus: 0,
            totalComments: 2,
            totalLikes: 1,
            body: "Temporarily... lol",
            imageStatus: 2,
            image: "",
            timePostedNarration: "Posted on December 8, 2024",
            timePosted: "Dec 8 2024",
            authorXuid: "2535471251948348",
            id: "userposts.xboxlive.com/users/xuid(2535471251948348)/posts/d17eba2c-3595-4c6e-bb13-bd576da6da4c/timelines/Club/3379879717831650",
        },
        {
            eventMetadata: "",
            eventZCoordinate: 0,
            eventYCoordinate: 0,
            eventXCoordinate: 0,
            eventHasCoordinates: false,
            eventPlayerXuids: [],
            isEventLoaded: false,
            isEvent: false,
            reportToXboxStatus: 0,
            reportToClubOwnerStatus: 0,
            deleteStatus: 0,
            toggleLikeStatus: 0,
            hasLiked: true,
            setViewedStatus: 0,
            hasViewed: true,
            commentsStatus: 0,
            totalComments: 2,
            totalLikes: 2,
            body: "I found your size addon and added it to voidless",
            imageStatus: 2,
            image: "",
            timePostedNarration: "Posted on September 11, 2024",
            timePosted: "Sep 11 2024",
            authorXuid: "2535438183245822",
            id: "userposts.xboxlive.com/users/xuid(2535438183245822)/posts/d3fd3f6f-a312-4667-94c2-c69590be8e74/timelines/Club/3379879717831650",
        },
        {
            eventMetadata: "",
            eventZCoordinate: 0,
            eventYCoordinate: 0,
            eventXCoordinate: 0,
            eventHasCoordinates: false,
            eventPlayerXuids: [],
            isEventLoaded: false,
            isEvent: false,
            reportToXboxStatus: 0,
            reportToClubOwnerStatus: 0,
            deleteStatus: 0,
            toggleLikeStatus: 0,
            hasLiked: false,
            setViewedStatus: 0,
            hasViewed: true,
            commentsStatus: 0,
            totalComments: 3,
            totalLikes: 3,
            body: "§l§cThe realm will be offline for a little bit longer due to the update breaking some of puffer's add-ons that were on here. ",
            imageStatus: 2,
            image: "",
            timePostedNarration: "Posted on September 2, 2024",
            timePosted: "Sep 2 2024",
            authorXuid: "2535440895442815",
            id: "userposts.xboxlive.com/users/xuid(2535440895442815)/posts/0f606efb-6a72-4310-b185-3369da2665d7/timelines/Club/3379879717831650",
        },
        {
            eventMetadata: "",
            eventZCoordinate: 0,
            eventYCoordinate: 0,
            eventXCoordinate: 0,
            eventHasCoordinates: false,
            eventPlayerXuids: [],
            isEventLoaded: false,
            isEvent: false,
            reportToXboxStatus: 0,
            reportToClubOwnerStatus: 0,
            deleteStatus: 0,
            toggleLikeStatus: 0,
            hasLiked: false,
            setViewedStatus: 0,
            hasViewed: true,
            commentsStatus: 0,
            totalComments: 0,
            totalLikes: 0,
            body: "how do i get out of the spwn?",
            imageStatus: 2,
            image: "",
            timePostedNarration: "Posted on August 29, 2024",
            timePosted: "Aug 29 2024",
            authorXuid: "2535468055639969",
            id: "userposts.xboxlive.com/users/xuid(2535468055639969)/posts/4d92b486-227f-4302-aa9b-de277797b611/timelines/Club/3379879717831650",
        },
        {
            eventMetadata: "",
            eventZCoordinate: 0,
            eventYCoordinate: 0,
            eventXCoordinate: 0,
            eventHasCoordinates: false,
            eventPlayerXuids: ["2535453842880200"],
            isEventLoaded: true,
            isEvent: true,
            reportToXboxStatus: 0,
            reportToClubOwnerStatus: 0,
            deleteStatus: 0,
            toggleLikeStatus: 0,
            hasLiked: false,
            setViewedStatus: 0,
            hasViewed: true,
            commentsStatus: 0,
            totalComments: 0,
            totalLikes: 2,
            body: "NewMember",
            imageStatus: 2,
            image: "",
            timePostedNarration: "Posted on August 25, 2024",
            timePosted: "Aug 25 2024",
            authorXuid: "2535443630523864",
            id: "userposts.xboxlive.com/users/xuid(2535443630523864)/posts/326a3d24-1652-4585-8252-60379d21a55e/timelines/Club/3379879717831650",
        },
        {
            eventMetadata: "",
            eventZCoordinate: 0,
            eventYCoordinate: 0,
            eventXCoordinate: 0,
            eventHasCoordinates: false,
            eventPlayerXuids: [],
            isEventLoaded: false,
            isEvent: false,
            reportToXboxStatus: 0,
            reportToClubOwnerStatus: 0,
            deleteStatus: 0,
            toggleLikeStatus: 0,
            hasLiked: true,
            setViewedStatus: 0,
            hasViewed: true,
            commentsStatus: 0,
            totalComments: 2,
            totalLikes: 2,
            body: "Realm will be rolled back to the day before 1.21.20 released very soon to fix things broken by the update. ",
            imageStatus: 2,
            image: "",
            timePostedNarration: "Posted on August 22, 2024",
            timePosted: "Aug 22 2024",
            authorXuid: "2535440895442815",
            id: "userposts.xboxlive.com/users/xuid(2535440895442815)/posts/4bd12fa4-4e26-4bbc-8e9f-dd2e19bbcf75/timelines/Club/3379879717831650",
        },
        {
            eventMetadata: "",
            eventZCoordinate: 0,
            eventYCoordinate: 0,
            eventXCoordinate: 0,
            eventHasCoordinates: false,
            eventPlayerXuids: [],
            isEventLoaded: false,
            isEvent: false,
            reportToXboxStatus: 0,
            reportToClubOwnerStatus: 0,
            deleteStatus: 0,
            toggleLikeStatus: 0,
            hasLiked: false,
            setViewedStatus: 0,
            hasViewed: true,
            commentsStatus: 0,
            totalComments: 0,
            totalLikes: 0,
            body: "A message to everyone, mostly blakers, it doesnt matter about the time, but about the effort, and in order to make gold, you must first realise what is cr4p and build from there.",
            imageStatus: 2,
            image: "",
            timePostedNarration: "Posted on August 12, 2024",
            timePosted: "Aug 12 2024",
            authorXuid: "2535413975095457",
            id: "userposts.xboxlive.com/users/xuid(2535413975095457)/posts/64d044c7-638a-4a17-bb09-4511749e2d73/timelines/Club/3379879717831650",
        },
    ],
});
