module.exports = () => ({
    realmsSubscriber: true,
    marketplacePassSubscriber: true,
    messagingServiceFailed: false,
    settings: {
        showOnlyFriendInvites: true,
        showMessageBadges: true,
        showInvitesBadges: true,
        showRealmsBadges: true,
        showNewsBadges: true,
        showMarketplacePassBadges: true,
        toggleInvitesBadges() {},
        toggleMessageBadges() {},
        toggleOnlyFriendInvites() {},
    },
    inboxMessages: [
        {
            id: "1",
            dateReceived: 1681687651,
            dateString: "11:35 am",
            dateLabel: "",
            title: "News :D",
            sender: "xKingDark",
            content: "Hello World!",
            read: false,
            announcementType: 0,
            imgSource: "/src/assets/screenshot4.png",
            buttons: [
                {
                    id: "",
                    text: "CTA Button",
                    link: "http://www.minecraft.net",
                    action: "external",
                    reportClick: () => {},
                },
            ],
        },
        {
            id: "2",
            dateReceived: 1681687651,
            dateString: "11:35 am",
            dateLabel: "",
            title: "Game Invite :D",
            sender: "xKingDark",
            content: "Hello World!",
            read: false,
            invitationId: "InvIdTest",
            announcementType: 1,
            imgSource: "/src/assets/screenshot4.png",
            invType: 2,
            invStatus: 0,
            template: "",
            instanceId: "2",
        },
        {
            id: "3",
            dateReceived: 1681687651,
            dateString: "11:35 am",
            dateLabel: "",
            title: "Realm Invite :D",
            sender: "xKingDark",
            content: "Hello World!",
            read: false,
            invitationId: "InvIdTest",
            announcementType: 2,
            imgSource: "/src/assets/screenshot4.png",
            invType: 2,
            invStatus: 0,
            template: "",
            instanceId: "3",
        },
        {
            id: "4",
            dateReceived: 1681687651,
            dateString: "11:35 am",
            dateLabel: "",
            title: "Marketplace Pass :D",
            sender: "xKingDark",
            content: "Hello World!",
            read: false,
            announcementType: 3,
            imgSource: "/src/assets/screenshot4.png",
        },
        {
            id: "4",
            dateReceived: 1681687651,
            dateString: "11:35 am",
            dateLabel: "",
            title: "Feedback :D",
            sender: "xKingDark",
            content: "Hello World!",
            read: true,
            announcementType: 4,
            imgSource: "/src/assets/screenshot4.png",
        },
    ],
    categoryUnreadMessages: {
        NEWS: 1,
        INVITES: 1,
        REALMS: 1,
        MARKETPLACEPASS: 1,
    },
    deleteNotification: (id) => id,
    saveSettings: () => {},
    setNotificationRead: () => {},
    categoryData: [
        { imageUrl: "id://606", unreadMessages: 3, localizedName: "News", categoryName: "news" },
        { imageUrl: "id://607", unreadMessages: 6, localizedName: "Realms", categoryName: "realms" },
        { imageUrl: "id://608", unreadMessages: 0, localizedName: "Invites", categoryName: "invites" },
        { imageUrl: "id://609", unreadMessages: 1, localizedName: "Marketplace Pass", categoryName: "marketplacepass" },
        { imageUrl: "id://610", unreadMessages: 0, localizedName: "Feedback", categoryName: "feedback" },
    ],
    acceptInvitation() {},
    rejectInvitation() {},
    reloadInvites() {},
    markAllRead() {},
    deleteAllRead() {},
    reportClick() {},
    requestMessages() {},
});

const a = {
    messagingServiceFailed: false,
    marketplacePassSubscriber: true,
    settings: { showOnlyFriendInvites: false, showMessageBadges: true, showInvitesBadges: true },
    categoryData: [
        { imageUrl: "id://606", unreadMessages: 3, localizedName: "News", categoryName: "news" },
        { imageUrl: "id://607", unreadMessages: 6, localizedName: "Realms", categoryName: "realms" },
        { imageUrl: "id://608", unreadMessages: 0, localizedName: "Invites", categoryName: "invites" },
        { imageUrl: "id://609", unreadMessages: 1, localizedName: "Marketplace Pass", categoryName: "marketplacepass" },
        { imageUrl: "id://610", unreadMessages: 0, localizedName: "Feedback", categoryName: "feedback" },
    ],
    realmsSubscriber: true,
    inboxMessages: [
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 1 },
            images: { length: 1 },
            template: "ImageText",
            worldId: "",
            instanceId: "845ec407-e74d-46f9-ad46-a9d2649a860a",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: false,
            inboxCategory: "news",
            content:
                "Craft a painting of the best canine companion a Steve could ask for and dance until the phantoms come out to the Lava Chicken music disc – out now in Java and Bedrock Edition! Get them both by simply updating Minecraft!",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "Canine art and catchy tunes",
            dateString: "7/21/2025",
            dateReceived: 1753123451,
            id: "845ec407-e74d-46f9-ad46-a9d2649a860a",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 2 },
            images: { length: 1 },
            template: "HeroImageCTA",
            worldId: "",
            instanceId: "796b9fc2-9dd8-4b11-81ad-dc951dd3c2fc",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: false,
            inboxCategory: "news",
            content:
                "Start your summer with great deals in Minecraft Marketplace! \n\nCheck in every day from July 1 to July 22 to get up to 75% off on select DLCs like worlds, add-ons, and skins. You can also dig into the world of the Hermits with your free copy of the Hermitcraft: Season 8 map. \n\nHere’s to summer fun!",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "Splash into the Summer Sale",
            dateString: "7/7/2025",
            dateReceived: 1751911809,
            id: "796b9fc2-9dd8-4b11-81ad-dc951dd3c2fc",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 2 },
            images: { length: 1 },
            template: "HeroImageCTA",
            worldId: "",
            instanceId: "31180a5e-f871-4ceb-8c54-02802a396eef",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: false,
            inboxCategory: "realms",
            content:
                "Rally your friends and set out on soaring adventures together with Realms Plus! Race your happy ghasts through sky-high builds, plan raids in the Nether, or marvel at the Vibrant Visuals sunsets with up to 10 friends on your own, always-online server. \n\nWith new content added to your Marketplace Pass catalog (included in Realms Plus) on release day you won't have to wait to fuel the fun. Subscribe to Realms Plus today!",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "Chase the Skies on Realms Plus",
            dateString: "7/7/2025",
            dateReceived: 1751911809,
            id: "31180a5e-f871-4ceb-8c54-02802a396eef",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 2 },
            images: { length: 1 },
            template: "HeroImageCTA",
            worldId: "",
            instanceId: "f37c774f-ffe3-4706-9946-6a756dd51614",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "news",
            content:
                "Welcome to the 1.21.100.23 Beta and Preview! For a complete changelog visit: aka.ms/MinecraftBeta and please search for any bugs you may find at bugs.mojang.com. Here are the highlights on what's in the update: \n\n• Experimental: Added the Copper Golem and Copper Chests\n• Experimental: Added Copper tools and armor\n• Fixed a bug that caused Happy Ghast to occasionally suffocate when faced against a wall\n• Boats once again retain momentum when moving off ledges\n\nPlease remember that worlds opened on Beta Preview builds cannot be reopened on previous builds. We recommend that you always make a copy of your worlds before opening them in the new update. Beta Preview players can only connect to other players on the same build version and do not have access to Realms. More information about joining and leaving the Beta Preview can be found at aka.ms/PreviewFAQ.",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "1.21.100.23 Beta Preview",
            dateString: "7/5/2025",
            dateReceived: 1751783880,
            id: "f37c774f-ffe3-4706-9946-6a756dd51614",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 17 },
            buttons: { length: 1 },
            images: { length: 18 },
            template: "ContentListNoCTA",
            worldId: "",
            instanceId: "486acb57-27be-4711-a436-008ba8b07d78",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: false,
            inboxCategory: "realms",
            content:
                "These add-ons, worlds, skin packs, and more are leaving soon from your Marketplace Pass, included with your Realms Plus subscription. Be sure to check them out before they're gone!",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "Some packs are leaving soon",
            dateString: "6/24/2025",
            dateReceived: 1750798346,
            id: "486acb57-27be-4711-a436-008ba8b07d78",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 2 },
            images: { length: 1 },
            template: "HeroImageCTA",
            worldId: "",
            instanceId: "be50225e-eed1-467b-a5c6-d8f8985ec195",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: false,
            inboxCategory: "news",
            content:
                "Experience the joy of soaring above the Overworld with our Chase the Skies drop! Fly with your happy ghast, leash a caravan of camels together, find wandering friends with the Player Locator bar, and more. Players on Bedrock Edition can also soak in breathtaking views with Minecraft's biggest official visual refresh – Vibrant Visuals. Play today!\n\nPlease note: some Marketplace content won't work with Vibrant Visuals, initially. They'll need some time to integrate— click the button to learn more!",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "Chase the Skies",
            dateString: "6/17/2025",
            dateReceived: 1750197387,
            id: "be50225e-eed1-467b-a5c6-d8f8985ec195",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 17 },
            buttons: { length: 1 },
            images: { length: 18 },
            template: "ContentListNoCTA",
            worldId: "",
            instanceId: "c76bee23-d27a-4fcb-8506-ce9594bf8e5b",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: false,
            inboxCategory: "realms",
            content: "There's new stuff to try in the Marketplace Pass catalog, available as part of your Realms Plus subscription. Check them out below.",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "See what's new for June",
            dateString: "6/3/2025",
            dateReceived: 1748973703,
            id: "c76bee23-d27a-4fcb-8506-ce9594bf8e5b",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 18 },
            buttons: { length: 1 },
            images: { length: 19 },
            template: "ContentListNoCTA",
            worldId: "",
            instanceId: "5d3cc452-7679-4893-be0c-64a5b172ef0e",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: false,
            inboxCategory: "realms",
            content:
                "These add-ons, worlds, skin packs, and more are leaving soon from your Marketplace Pass, included with your Realms Plus subscription. Be sure to check them out before they're gone!",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "Some packs are leaving soon",
            dateString: "5/23/2025",
            dateReceived: 1748042665,
            id: "5d3cc452-7679-4893-be0c-64a5b172ef0e",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 21 },
            buttons: { length: 1 },
            images: { length: 22 },
            template: "ContentListNoCTA",
            worldId: "",
            instanceId: "61a2f988-fc74-435c-817b-deaffbd87650",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: false,
            inboxCategory: "marketplacepass",
            content:
                "There's new stuff to try in the Marketplace Pass catalog, including Actions and Stuff! Get custom animations, textures, 3D models, and so much more. Check out the full list below.",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "See what's new for May",
            dateString: "5/13/2025",
            dateReceived: 1747164212,
            id: "61a2f988-fc74-435c-817b-deaffbd87650",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 2 },
            images: { length: 1 },
            template: "HeroImageCTA",
            worldId: "",
            instanceId: "4e156e5d-2328-498d-9da7-e4d8f95c3952_1746551495",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "news",
            content:
                "Thanks for signing in. Your free Common Cape awaits! Besides this, you can now play cross-platform with your friends on a Realm, access your marketplace content across different game platforms, and track your achievements.",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "Your new cape and more",
            dateString: "5/6/2025",
            dateReceived: 1746551495,
            id: "4e156e5d-2328-498d-9da7-e4d8f95c3952",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 20 },
            buttons: { length: 1 },
            images: { length: 21 },
            template: "ContentListNoCTA",
            worldId: "",
            instanceId: "40dbd2f8-a93e-47b1-a19a-3f5656ed0ce1",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: false,
            inboxCategory: "realms",
            content:
                "These add-ons, worlds, skin packs, and more are leaving soon from your Marketplace Pass, included with your Realms Plus subscription. Be sure to check them out before they're gone!",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "Some packs are leaving soon",
            dateString: "4/15/2025",
            dateReceived: 1744758814,
            id: "40dbd2f8-a93e-47b1-a19a-3f5656ed0ce1",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 24 },
            buttons: { length: 1 },
            images: { length: 25 },
            template: "ContentListNoCTA",
            worldId: "",
            instanceId: "2cf6678d-b40b-4968-a03f-09970182f7fd",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: false,
            inboxCategory: "realms",
            content: "There's new stuff to try in the Marketplace Pass catalog, available as part of your Realms Plus subscription. Check them out below.",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "See what's new for April",
            dateString: "4/8/2025",
            dateReceived: 1744147640,
            id: "2cf6678d-b40b-4968-a03f-09970182f7fd",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 2 },
            images: { length: 1 },
            template: "HeroImageCTA",
            worldId: "",
            instanceId: "7080532c-5515-461b-93c5-57cc2e4ee757",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "news",
            content:
                "Welcome to the 1.21.80.22 Beta and Preview! For a complete changelog visit: aka.ms/MinecraftBeta and please search for any bugs you may find at bugs.mojang.com. Here are the highlights on what's in the update: \n\n• Experimental: Spectators now appear to other Spectators on the Player Locator bar\n• Added flat world presets! Choose from a selection of presets to define how your flat worlds look!\n• Fixed an issue where the player would momentarily lay under or beside a Bed when going to sleep\n• Mobs no longer have difficulty inflicting recurring hits when very close to non-moving players\n\nPlease remember that worlds opened on Beta Preview builds cannot be reopened on previous builds. We recommend that you always make a copy of your worlds before opening them in the new update. Beta Preview players can only connect to other players on the same build version and do not have access to Realms. More information about joining and leaving the Beta Preview can be found at aka.ms/PreviewFAQ.",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "1.21.80.22 Beta Preview",
            dateString: "3/26/2025",
            dateReceived: 1743013809,
            id: "7080532c-5515-461b-93c5-57cc2e4ee757",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 20 },
            buttons: { length: 1 },
            images: { length: 21 },
            template: "ContentListNoCTA",
            worldId: "",
            instanceId: "e67f5844-dcaa-4d07-9608-b62087edf2d9",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "realms",
            content:
                "These add-ons, worlds, skin packs, and more are leaving soon from your Marketplace Pass, included with your Realms Plus subscription. Be sure to check them out before they're gone!",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "Some packs are leaving soon",
            dateString: "3/11/2025",
            dateReceived: 1741730734,
            id: "e67f5844-dcaa-4d07-9608-b62087edf2d9",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 24 },
            buttons: { length: 1 },
            images: { length: 25 },
            template: "ContentListNoCTA",
            worldId: "",
            instanceId: "74a3e5b7-b5ee-4e73-bc5f-e18689bd8fab",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "realms",
            content:
                "Each gaming session is an adventure with the Marketplace Pass, included with your new Realms Plus subscription! Discover 150+ pieces of content like worlds, skin packs, and more – refreshed monthly. Check out some of our favorite packs listed below!",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "Your New Content",
            dateString: "2/14/2025",
            dateReceived: 1739568243,
            id: "74a3e5b7-b5ee-4e73-bc5f-e18689bd8fab",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 1 },
            images: { length: 1 },
            template: "ImageText",
            worldId: "",
            instanceId: "86ecc35d-dc14-41ab-9da7-d5167d67e0f8",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "news",
            content:
                "Great news: Minecraft R21u6 is finally here! \n\nWe've added new features to the experimental toggle for you to try in Java snapshot and Bedrock beta/preview, including falling leaf particles, changes to the lodestone, and best of all, warm and cold pig variants! Who doesn't want a cute fluffy pig?!\n\nThere's also been over 200 bug fixes and tweaks to improve your gameplay experience. You can see the full list of changes at aka.ms/MinecraftUpdate\n\nPlease be sure to report any new bugs you find at bugs.mojang.com and leave us your feedback at feedback.minecraft.net!",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "Minecraft 1.21.60 Update",
            dateString: "2/11/2025",
            dateReceived: 1739309160,
            id: "86ecc35d-dc14-41ab-9da7-d5167d67e0f8",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 2 },
            images: { length: 1 },
            template: "HeroImageCTA",
            worldId: "",
            instanceId: "38d01d73-5fef-442a-829a-4fc36cd8ca96",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "news",
            content:
                "Ready to roll around at the speed of sound? Do you have places to go, and you gotta go fast?\n\nDo I have an add-on for you... the Sonic Add-On! Play as Sonic, Tails, Knuckles, Amy, and Shadow in any of your worlds.\n\nSmash blocks with a spin-dash, collect rings, take down enemies, and go so fast you run on water. Become the blue blur today!",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "Zoom into the Sonic add-on",
            dateString: "2/5/2025",
            dateReceived: 1738801410,
            id: "38d01d73-5fef-442a-829a-4fc36cd8ca96",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 2 },
            images: { length: 1 },
            template: "HeroImageCTA",
            worldId: "",
            instanceId: "82a2b803-955d-480d-9cc8-77962277bcb7",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "news",
            content:
                "Start off the Year of the Snake with cool content and freebies in Minecraft Marketplace! \n\nExplore a curated collection of Lunar New Year packs from January 28 10am PT to February 4 10am PT and grab your free copy of the map Wukong: Uproar in Heaven.\n\nYou can also claim your free Hello Kitty® Lantern Banner in the Dressing Room, perfect to wear when playing the Hello Kitty and Friends DLC (sold separately). Happy Lunar New Year!",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "Celebrate Lunar New Year",
            dateString: "1/28/2025",
            dateReceived: 1738108098,
            id: "82a2b803-955d-480d-9cc8-77962277bcb7",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 2 },
            images: { length: 1 },
            template: "HeroImageCTA",
            worldId: "",
            instanceId: "d05f271b-e960-4c6d-a1fa-98966e55ae5e",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "news",
            content:
                "Step into the world of Hello Kitty in this charming DLC, where farming meets friendship! Create your own cozy farm alongside Hello Kitty, Cinnamoroll, Kuromi, and many more.\n\nYou can also upgrade your home with over 180 new furniture options for lots of added charm and enjoy seasonal events like spring egg hunts and fall pumpkin carving. Enjoy the sweetest simulation today!",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "Hello Kitty and Friends DLC",
            dateString: "1/21/2025",
            dateReceived: 1737492493,
            id: "d05f271b-e960-4c6d-a1fa-98966e55ae5e",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 2 },
            images: { length: 1 },
            template: "HeroImageCTA",
            worldId: "",
            instanceId: "d10ba7ce-44dc-4009-9483-c6fb3b8e2024",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "news",
            content:
                "This chicken got cooked – will you? Feast on some lava chicken,  like Steve’s recipe in A Minecraft Movie, to turn up the heat and leave a... spicy trail for your foes. Can you win the battle before the heat overwhelms you? Get the free add-on at Minecraft Marketplace and test your cooking skills. Stay tuned for more exciting A Minecraft Movie content... Now dig in!",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "Lava Chicken Add-on",
            dateString: "12/28/2024",
            dateReceived: 1735377906,
            id: "d10ba7ce-44dc-4009-9483-c6fb3b8e2024",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 2 },
            images: { length: 1 },
            template: "HeroImageCTA",
            worldId: "",
            instanceId: "1f672086-a925-416e-8bbe-043dd4afcf11",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "news",
            content:
                "Start your new year with new ways to play! From 10 am PT on December 19 to 10 am PT on January 7, 2025, you can get great digital deals of up to 75% off and the Soundscapes+ add-on for free! \n\nWant to introduce your blocky worlds to a new you this new year? Then hit the Dressing Room and fill your closet with select Character Creator items for 33% off. Enjoy the New Year’s Sale today!",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "New Year's Sale at Marketplace",
            dateString: "12/19/2024",
            dateReceived: 1734668316,
            id: "1f672086-a925-416e-8bbe-043dd4afcf11",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 1 },
            images: { length: 1 },
            template: "ImageText",
            worldId: "",
            instanceId: "439834c0-2d71-40d0-8b99-dcbf99b89777",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "news",
            content:
                "I heard a rumor that the creaking mob can be... created?? Rumor has it that by crafting a creaking heart block and placing it between two logs, adventurers will be rewarded with a special Creaking Heart Shirt. I don't want to wear clothes from that creepy mob, but maybe you do.  And of course, with the reward comes the risk... once you've made the creaking, you might want to run.",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "Rumors of a special shirt",
            dateString: "12/11/2024",
            dateReceived: 1733966561,
            id: "439834c0-2d71-40d0-8b99-dcbf99b89777",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 1 },
            images: { length: 1 },
            template: "ImageText",
            worldId: "",
            instanceId: "a89633ab-2553-4864-8c23-08fc66a9533f",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "news",
            content:
                "A strange new biome has spread across the Overworld, cloaked in pale moss and filled with unseen eyes. I haven’t seen its denizens… but I can feel them. Watching. Waiting.\n\nIf you must enter, I’ve left supplies. Find clothes in the Dressing Room, event plans, and an add-on for defense. Keep an eye out for the supplies over the course of this week… and watch your back in the pale garden. Always.",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "STAY. OUT.",
            dateString: "12/6/2024",
            dateReceived: 1733494388,
            id: "a89633ab-2553-4864-8c23-08fc66a9533f",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 2 },
            images: { length: 1 },
            template: "HeroImageCTA",
            worldId: "",
            instanceId: "e1315976-0fb2-41e7-88c4-2491031604fb",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "news",
            content:
                "Block Friday returns for its seventh year in a row! Head to the Marketplace for great digital deals of up to 75% off. \n\nThe sale runs every day from 10 am PST on November 26 to 10 am PST on December 3, so be sure to “block” off your calendars!",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "The Block Friday Sale is back",
            dateString: "12/3/2024",
            dateReceived: 1733246319,
            id: "e1315976-0fb2-41e7-88c4-2491031604fb",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 21 },
            buttons: { length: 1 },
            images: { length: 22 },
            template: "ContentListNoCTA",
            worldId: "",
            instanceId: "8f7d4de0-92dc-4141-9bc0-1db5bd5893a5",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "marketplacepass",
            content: "There's new stuff to try in the Marketplace Pass catalog, available as part of your Realms Plus subscription. Check them out below.",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "See what's new for November",
            dateString: "11/5/2024",
            dateReceived: 1730862298,
            id: "8f7d4de0-92dc-4141-9bc0-1db5bd5893a5",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 2 },
            images: { length: 1 },
            template: "HeroImageCTA",
            worldId: "",
            instanceId: "1d8e3205-d52b-4a18-a5cc-d16047d2c041",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "news",
            content:
                "Welcome to the 1.21.50.20 Beta and Preview! For a complete changelog visit: aka.ms/MinecraftBeta and please search for any bugs you may find at bugs.mojang.com. Here are the highlights on what's in the update: \n\n• Added some of the Winter Drop features, including the Pale Garden biome and the Creaking mob\n• Swords can now cut Bamboo Saplings instantly, as they do Bamboo\n• Foxes can now pick up Bundles\n\nPlease remember that worlds opened on Beta Preview builds cannot be reopened on previous builds. We recommend that you always make a copy of your worlds before opening them in the new update. Beta Preview players can only connect to other players on the same build version and do not have access to Realms. More information about joining and leaving the Beta Preview can be found at aka.ms/PreviewFAQ.",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "1.21.50.20 Beta Preview",
            dateString: "10/10/2024",
            dateReceived: 1728594003,
            id: "1d8e3205-d52b-4a18-a5cc-d16047d2c041",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 20 },
            buttons: { length: 1 },
            images: { length: 21 },
            template: "ContentListNoCTA",
            worldId: "",
            instanceId: "53d0152f-781c-4dc3-b6ff-7870b5ad090f",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "marketplacepass",
            content: "There's new stuff to try in the Marketplace Pass catalog, available as part of your Realms Plus subscription. Check them out below.",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "See what's new for October",
            dateString: "10/8/2024",
            dateReceived: 1728427171,
            id: "53d0152f-781c-4dc3-b6ff-7870b5ad090f",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 2 },
            images: { length: 1 },
            template: "HeroImageCTA",
            worldId: "",
            instanceId: "ad190b19-a09e-40b1-894b-4b5d577e8784",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "news",
            content:
                "Welcome to the 1.21.40.22 Beta and Preview! For a complete changelog visit: aka.ms/MinecraftBeta and please search for any bugs you may find at bugs.mojang.com. Here are the highlights on what's in the update: \n\n• Experimental: Bundles can now be dyed 16 different colors!\n• Jump Boost now increases how high a Breeze can jump\n• Fixed double input when using analog triggers on certain gamepads\n\nPlease remember that worlds opened on Beta Preview builds cannot be reopened on previous builds. We recommend that you always make a copy of your worlds before opening them in the new update. Beta Preview players can only connect to other players on the same build version and do not have access to Realms. More information about joining and leaving the Beta Preview can be found at aka.ms/PreviewFAQ.",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "1.21.40.22 Beta Preview",
            dateString: "9/21/2024",
            dateReceived: 1726966731,
            id: "ad190b19-a09e-40b1-894b-4b5d577e8784",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 1 },
            images: { length: 1 },
            template: "ImageText",
            worldId: "",
            instanceId: "44724a4e-798c-48ed-832f-1779fc47bd47",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "realms",
            content:
                "There's lots of Realms Events to achieve, but let's talk about the coolest one in the hottest climate - finding a nether fortress! I know they may sound intimidating, but they're not, really. Unless, of course, you find lots of lava, giant winding buildings with tons of twists and turns, and fireball-throwing mobs intimidating. In that case, they're actually terrifying!\n\nNow, finding a nether fortress can be a little tricky, but bringing your friends can make it easier. (Unless you're bringing Jerry. Last time he went to the Nether he tried to place a bed and sleep through the non-existent night.) \n\nTypically, nether fortresses spawn along the north-south axis in the Nether, so once you've gotten through the portal, focus on traveling either north or south. If your party is pretty proficient in not falling into lava or getting blasted by ghasts, you may choose to split up and search in different directions to cover more ground.\n\nLastly, make sure you and your friends are well-prepared before you go fortress hunting. Equip yourselves with armor (enchanted netherite would be best), a bow for ranged attacks (don't forget your arrows), and bring plenty of food (I recommend golden carrots, but hey, bring the suspicious stew if you want).\n\nWith some teamwork and a little luck, you’ll have those blaze rods and nether wart in no time. Then you'll just need to head back to the Overworld – hey, where did you leave that nether portal, exactly?",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "Realms Events: Finding a nether fortress",
            dateString: "9/16/2024",
            dateReceived: 1726528868,
            id: "44724a4e-798c-48ed-832f-1779fc47bd47",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 2 },
            images: { length: 1 },
            template: "HeroImageCTA",
            worldId: "",
            instanceId: "7395b5a3-7eff-4a21-8e97-0d3e0b4099dc",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "news",
            content:
                "Welcome to the 1.21.40.20 Beta Preview! For a complete changelog visit: aka.ms/Minecraft Beta and please search for any bugs you may find at bugs.mojang.com. Here are the highlights on what's in the update: \n\n• Experimental: When a Bundle is used in the hotbar, one group of items is emptied at a time instead of everything being emptied at once\n• Experimental: Using a Bundle from the hotbar now plays a sound and triggers an animation when emptying items\n• Wolves, Cats, and Parrots now teleport to their owner when panicking and far enough away\n\nPlease remember that worlds opened on Beta Preview builds cannot be reopened on previous builds. We recommend that you always make a copy of your worlds before opening them in the new update. Beta Preview players can only connect to other players on the same build version and do not have access to Realms. More information about joining and leaving the Beta Preview can be found at aka.ms/PreviewFAQ.",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "1.21.40.20 Beta Preview",
            dateString: "9/6/2024",
            dateReceived: 1725667502,
            id: "7395b5a3-7eff-4a21-8e97-0d3e0b4099dc",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 2 },
            images: { length: 2 },
            template: "ImageThumbnailCTA",
            worldId: "",
            instanceId: "9edf9ef1-acca-46c9-9017-76b194efdea9",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "realms",
            content:
                "Recently, we experienced an outage with our Realms servers. We've since fixed the issue, and we are grateful for your patience as we worked through it. While we are unable to give you back lost time, we've given you access to the Bedrock Bingo Item Hunt DLC and 660 Minecoins to show our appreciation for your patience and love of Minecraft. Additionally, we've increased Realms render distance from 20 to 25, and we hope this newfound vision boost serves you well. \n\nThank you for being a continued part of our community. You're a huge part of what makes our blocky little game so special, and we hope you enjoy your new content.",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "Realms Update",
            dateString: "8/27/2024",
            dateReceived: 1724800075,
            id: "9edf9ef1-acca-46c9-9017-76b194efdea9",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 2 },
            images: { length: 1 },
            template: "HeroImageCTA",
            worldId: "",
            instanceId: "ce44485f-8dea-4972-8e62-d43400614f6e",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "news",
            content:
                "Welcome to the 1.21.30.23 Beta Preview! For a complete changelog visit: aka.ms/Minecraft Beta and please search for any bugs you may find at bugs.mojang.com. Here are the highlights on what's in the update: \n\n• Experimental: Added Bundles, which can be crafted with String and Leather\n• Parrots can now imitate Endermites and Drowned\n• Fixed an issue where End Gateway Portals could teleport some players incorrectly\n\nPlease remember that worlds opened on Beta Preview builds cannot be reopened on previous builds. We recommend that you always make a copy of your worlds before opening them in the new update. Beta Preview players can only connect to other players on the same build version and do not have access to Realms. More information about joining and leaving the Beta Preview can be found at aka.ms/PreviewFAQ.",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "1.21.30.23 Beta Preview",
            dateString: "8/15/2024",
            dateReceived: 1723741358,
            id: "ce44485f-8dea-4972-8e62-d43400614f6e",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 2 },
            images: { length: 1 },
            template: "HeroImageCTA",
            worldId: "",
            instanceId: "8789ee8e-854a-4747-ad05-8aef4ba1b781",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "news",
            content:
                "Welcome to the 1.21.30.22 Beta Preview! For a complete changelog visit: aka.ms/Minecraft Beta and please search for any bugs you may find at bugs.mojang.com. Here are the highlights on what's in the update: \n\n• Fixed the collision shape for Trial Spawners; it is now the same size as an ordinary block\n• Added a new death message for when players are defeated by a Mace smash attack\n• Updated the names of many items and blocks, to bring them closer to parity with Java Edition\n\nPlease remember that worlds opened on Beta Preview builds cannot be reopened on previous builds. We recommend that you always make a copy of your worlds before opening them in the new update. Beta Preview players can only connect to other players on the same build version and do not have access to Realms. More information about joining and leaving the Beta Preview can be found at aka.ms/PreviewFAQ.",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "1.21.30.22 Beta Preview",
            dateString: "8/9/2024",
            dateReceived: 1723230597,
            id: "8789ee8e-854a-4747-ad05-8aef4ba1b781",
        },
        {
            style: 0,
            gamedrop: null,
            items: { length: 0 },
            buttons: { length: 2 },
            images: { length: 1 },
            template: "HeroImageCTA",
            worldId: "",
            instanceId: "66a4f9eb-d68c-430a-9eb5-541b90d9c51f",
            invStatus: 0,
            expiryDaysLeft: null,
            invType: 0,
            imgSource: "",
            invitationId: "",
            read: true,
            inboxCategory: "realms",
            content:
                "With Realms, you get your own personal server, and you can invite up to 10 friends to play with you.\n\nYou can keep in touch with your fellow players using Realms Stories: a new in-game social feed that lets you connect, build, and celebrate together, even when you're far apart! \n\nA Realms Plus subscription also comes with a catalog of things you can try out from Marketplace including skins, worlds, add-ons, and more. What are you waiting for? Grab your friends and start a new adventure with Realms today.",
            senderXuid: "",
            sender: "Minecraft",
            subtitle: "",
            title: "Start a new Realms adventure",
            dateString: "7/11/2024",
            dateReceived: 1720726526,
            id: "66a4f9eb-d68c-430a-9eb5-541b90d9c51f",
        },
    ],
};

